apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: external-dns
--- 
apiVersion: v1
data:
  azure.json: ew0KICAidGVuYW50SWQiOiAiMTY5YzU2NDEtMGFjNy00ZGE5LThjZmEtODVhY2UxNmI0ZjY5IiwNCiAgInN1YnNjcmlwdGlvbklkIjogImI2NjVkZGU5LTk5Y2UtNGRmZS05ODBhLTYwYWE1OTlkMjEyOSIsDQogICJyZXNvdXJjZUdyb3VwIjogInJnLXBvYy1ha3MtaW5mcmFzdHJ1Y3R1cmUiLCANCiAgInVzZU1hbmFnZWRJZGVudGl0eUV4dGVuc2lvbiI6IHRydWUsDQogICJ1c2VyQXNzaWduZWRJZGVudGl0eUlEIjogImEwOTJiOGQ1LWI1MDgtNDdiZC04M2NlLTJlZTA0NWIwZDRiNyINCg0KfQ0K
kind: Secret
metadata:
  creationTimestamp: null
  name: azure-config-file
  namespace: external-dns
  