apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-infra
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/stromberg2/argocd.git
    targetRevision: HEAD
    path: k8s-infra
  destination:
    server: https://kubernetes.default.svc
    namespace: k8s-infra
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
    - CreateNamespace=true  