apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-cpr
spec:  
  ingressClassName: nginx
  rules:
  - host: eapp1.gsbonazure.de
    http:
      paths:
      - path: /app1
        pathType: Prefix
        backend:
          service:
            name: app1-nginx-clusterip-service
            port: 
              number: 80  

